// Catalog generator: snapshots real OSRS GE data into packages/engine/src/catalog.ts
// and downloads item icons. Build-time only — the engine stays deterministic.
//   npm run gen:catalog [-- --count 48]
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..', '..', '..');
const UA = 'exchange-wars-catalog-gen/1.0 (https://github.com/kalilinux1993/exchange-wars)';

function arg(name: string, fallback: number): number {
  const i = process.argv.indexOf(`--${name}`);
  return i === -1 || i === process.argv.length - 1 ? fallback : Number(process.argv[i + 1]);
}

const STAPLES = arg('staples', 40);
const EXOTICS = arg('exotics', 12);
const EXOTIC_MIN_PRICE = 20_000;
const EXOTIC_VOLATILITY = 0.13; // above tier-2's 0.12 ceiling — tier-3 territory

interface MapEntry {
  id: number;
  name: string;
  limit?: number;
  icon?: string;
  members?: boolean;
}

async function getJson<T>(url: string): Promise<T> {
  const res = await fetch(url, { headers: { 'User-Agent': UA } });
  if (!res.ok) throw new Error(`${url} -> HTTP ${res.status}`);
  return (await res.json()) as T;
}

function slug(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '_')
    .replace(/^_+|_+$/g, '');
}

function tierVolatility(price: number): number {
  if (price < 100) return 0.08;
  if (price < 1_000) return 0.09;
  if (price < 10_000) return 0.1;
  if (price < 100_000) return 0.08;
  return 0.06;
}

const mapping = await getJson<MapEntry[]>('https://prices.runescape.wiki/api/v1/osrs/mapping');
const latest = await getJson<{ data: Record<string, { high: number | null; low: number | null }> }>(
  'https://prices.runescape.wiki/api/v1/osrs/latest',
);
const volumes = await getJson<{ data: Record<string, number> }>(
  'https://prices.runescape.wiki/api/v1/osrs/volumes',
);

const candidates = mapping
  .map((m) => {
    const p = latest.data[String(m.id)];
    const vol = volumes.data[String(m.id)] ?? 0;
    const price = p && p.high !== null && p.low !== null ? Math.round((p.high + p.low) / 2) : 0;
    return { m, price, vol };
  })
  .filter(
    ({ m, price, vol }) =>
      (m.limit ?? 0) > 0 && m.icon !== undefined && price >= 30 && price <= 10_000_000 && vol > 0,
  )
  .sort((a, b) => b.vol - a.vol);

// Two tracks: liquid staples by raw volume, plus high-ticket "exotics" so the
// price ladder has a top end and tier-3 automation has a niche (vol 0.13 is
// above tier-2's 0.12 ceiling — exotic books are tier-3/human territory).
const staples = candidates.slice(0, STAPLES);
const stapleIds = new Set(staples.map((c) => c.m.id));
const exotics = candidates
  .filter((c) => !stapleIds.has(c.m.id) && c.price >= EXOTIC_MIN_PRICE)
  .slice(0, EXOTICS);

const picked = [...staples, ...exotics.map((e) => ({ ...e, exotic: true as const }))]
  .map((c) => ({ ...c, exotic: 'exotic' in c && c.exotic === true }))
  .map(({ m, price, exotic }) => ({
    id: slug(m.name),
    name: m.name,
    baseCost: Math.max(1, Math.round(price * 0.75)),
    consumeValue: Math.max(2 * Math.max(1, Math.round(price * 0.75)), Math.round(price * 1.5)),
    volatility: exotic ? EXOTIC_VOLATILITY : tierVolatility(price),
    wikiId: m.id,
    wikiPrice: price,
    buyLimit: m.limit ?? 0,
    icon: m.icon!,
  }))
  .sort((a, b) => a.baseCost - b.baseCost);

// De-dupe slugs (e.g. potion dose variants can collide after slugging).
const seen = new Set<string>();
const items = picked.filter((i) => (seen.has(i.id) ? false : (seen.add(i.id), true)));

const lines = items
  .map(
    (i) =>
      `  { id: '${i.id}', name: ${JSON.stringify(i.name)}, baseCost: ${i.baseCost}, consumeValue: ${i.consumeValue}, volatility: ${i.volatility}, wikiId: ${i.wikiId}, wikiPrice: ${i.wikiPrice}, buyLimit: ${i.buyLimit} },`,
  )
  .join('\n');

const file = `import type { ItemDef } from './types';

// GENERATED by \`npm run gen:catalog\` — do not hand-edit.
// Snapshot of real OSRS GE data from prices.runescape.wiki (anchors derived:
// baseCost ≈ 0.75×price, consumeValue ≈ 1.5×price, volatility by price tier).
// Regenerating re-rolls every seeded world: re-run the tier-1 sweep + gates.
export const DEFAULT_ITEMS: ItemDef[] = [
${lines}
];
`;

writeFileSync(join(ROOT, 'packages', 'engine', 'src', 'catalog.ts'), file, 'utf8');
console.log(
  `catalog.ts written: ${items.length} items, ${items.filter((i) => i.volatility === EXOTIC_VOLATILITY).length} exotic (${items[0]?.name} … ${items[items.length - 1]?.name})`,
);

const iconDir = join(ROOT, 'packages', 'ui', 'public', 'icons');
mkdirSync(iconDir, { recursive: true });
let ok = 0;
for (const i of items) {
  const url = `https://oldschool.runescape.wiki/images/${encodeURIComponent(i.icon.replace(/ /g, '_'))}`;
  try {
    const res = await fetch(url, { headers: { 'User-Agent': UA } });
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    writeFileSync(join(iconDir, `${i.wikiId}.png`), Buffer.from(await res.arrayBuffer()));
    ok++;
    await new Promise((r) => setTimeout(r, 120)); // politeness
  } catch (e) {
    console.warn(`icon failed for ${i.name}: ${(e as Error).message}`);
  }
}
console.log(`icons downloaded: ${ok}/${items.length}`);
